esphome:
  name: tab5-ha-dash
  friendly_name: Tab5 Dashboard
  min_version: 2025.12.0

esp32:
  variant: esp32p4
  flash_size: 16MB
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

packages:
  remote_package_files:
      url: https://github.com/ContemptibleCat/m5tab5configs
      files: [ tab5-globals.yaml, tab5-lvgl.yaml, tab5-scripts.yaml]

external_components:
  - source: github://pr#12075
    components: [st7123]
    refresh: 1h
  - source: github://pr#12074
    components: [mipi_dsi]
    refresh: 1h

esp32_hosted:
  variant: esp32c6
  active_high: true
  clk_pin: GPIO12
  cmd_pin: GPIO13
  d0_pin: GPIO11
  d1_pin: GPIO10
  d2_pin: GPIO9
  d3_pin: GPIO8
  reset_pin: GPIO15
  slot: 1

logger:
  hardware_uart: USB_SERIAL_JTAG

psram:
  mode: hex
  speed: 200MHz

api:
  on_client_connected: 
    then:
      - lvgl.widget.show: api_icon_label
  on_client_disconnected: 
    then:
      - lvgl.widget.hide: api_icon_label
  encryption:
    key: !secret ha_key

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  on_connect: 
    then:
      - lvgl.widget.show: wifi_icon_label
  on_disconnect: 
    then:
      - lvgl.widget.hide: wifi_icon_label

i2c:
  - id: bsp_bus
    sda: GPIO31
    scl: GPIO32
    frequency: 400kHz

rc522_i2c:
  address: 0x28
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return x;'

pi4ioe5v6408:
  - id: pi4ioe1
    address: 0x43
    # 0: O - wifi_antenna_int_ext
    # 1: O - speaker_enable
    # 2: O - external_5v_power
    # 3: NC
    # 4: O - lcd reset
    # 5: O - touch panel reset
    # 6: O - camera reset
    # 7: I - headphone detect
  - id: pi4ioe2
    address: 0x44
    # 0: O - wifi_power
    # 1: NC
    # 2: NC
    # 3: O - usb_5v_power
    # 4: O - poweroff pulse
    # 5: O - quick charge enable (inverted)
    # 6: I - charging status
    # 7: O - charge enable

switch:
  - platform: gpio
    id: wifi_power
    name: "WiFi Power"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 0
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: usb_5v_power
    name: "USB Power"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 3
  - platform: gpio
    id: quick_charge
    name: "Quick Charge"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 5
      inverted: true
  - platform: gpio
    id: charge_enable
    name: "Charge Enable"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 7
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: wifi_antenna_int_ext
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 0
  - platform: gpio
    id: speaker_enable
    name: "Speaker Enable"
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 1
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: external_5v_power
    name: "External 5V Power"
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 2

binary_sensor:
  - platform: gpio
    id: charging
    name: "Charging Status"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 6
      mode: INPUT_PULLDOWN
    on_press:
      - lambda: id(battery_percent).update();
    on_release:
      - lambda: id(battery_percent).update();

  - platform: gpio
    id: headphone_detect
    name: "Headphone Detect"
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 7

select:
# The DAC Output select needs to be manually 
# (or with an automation) changed to `LINE1` for the onboard speaker
  - platform: es8388
    dac_output:
      name: DAC Output
    adc_input_mic:
      name: ADC Input Mic

  - platform: template
    id: wifi_antenna_select
    name: "WiFi Antenna"
    options:
      - "Internal"
      - "External"
    optimistic: true
    on_value:
      - if:
          condition:
            lambda: return i == 0;
          then:
            - switch.turn_off: wifi_antenna_int_ext
          else:
            - switch.turn_on: wifi_antenna_int_ext

sensor:
  - platform: ina226
    address: 0x41
    adc_averaging: 16
    max_current: 8.192A
    shunt_resistance: 0.005ohm
    bus_voltage:
      id: battery_voltage
      name: Battery Voltage
    current:
      id: battery_current
      name: Battery Current
      # Positive means discharging
      # Negative means charging
  
  - platform: homeassistant
    id: cur_temp
    entity_id: sensor.hub_temperature
    on_value:
      - lvgl.label.update:
          id: temp_label
          text:
            format: "%.1f °C"
            args: [ 'x' ]
  
  - platform: homeassistant
    id: cur_humi
    entity_id: sensor.hub_humidity
    on_value:
      - lvgl.label.update:
          id: humi_label
          text:
            format: "%.1f %%"
            args: [ 'x' ]

  - platform: template
    id: battery_percent
    name: "Battery Percentage"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      float voltage = id(battery_voltage).state;
      float min_voltage = 6.0;
      float max_voltage = 8.4;
      
      if (voltage < 5.0) return 0.0;
      if (voltage <= min_voltage) return 0.0;
      if (voltage >= max_voltage) return 100.0;
      
      float percent = ((voltage - min_voltage) / (max_voltage - min_voltage)) * 100.0;
      return percent;
    update_interval: 10s
    on_value:
      - lvgl.label.update:
          id: pwr_bat_icon_label
          text: !lambda |-
            float voltage = id(battery_voltage).state;
            float current = id(battery_current).state;
            bool charging_pin = id(charging).state;
            int level = int(x);
            
            // No battery detected
            if (voltage < 5.0) {
              return "\U000F06A5";  // Plug icon
            }
            
            // Determine which icon set to use based on charging status
            bool is_charging = (current < -0.1 || charging_pin);
            
            // Use level/10 to create brackets: 0-9=0, 10-19=1, 20-29=2, etc.
            int bracket = level / 10;
            
            if (is_charging) {
              // Charging icons
              switch (bracket) {
                case 10:
                case 9:
                  return "\U000F0085";  // charging-100
                case 8:
                  return "\U000F008B";  // charging-90
                case 7:
                  return "\U000F008A";  // charging-80
                case 6:
                  return "\U000F089E";  // charging-70
                case 5:
                  return "\U000F0089";  // charging-60
                case 4:
                  return "\U000F089D";  // charging-50
                case 3:
                  return "\U000F0088";  // charging-40
                case 2:
                  return "\U000F0087";  // charging-30
                case 1:
                  return "\U000F0086";  // charging-20
                default:
                  return "\U000F089C";  // charging-10
              }
            } else {
              // Regular battery icons
              switch (bracket) {
                case 10:
                case 9:
                  return "\U000F0079";  // battery-100
                case 8:
                  return "\U000F0082";  // battery-90
                case 7:
                  return "\U000F0081";  // battery-80
                case 6:
                  return "\U000F0080";  // battery-70
                case 5:
                  return "\U000F007F";  // battery-60
                case 4:
                  return "\U000F007E";  // battery-50
                case 3:
                  return "\U000F007D";  // battery-40
                case 2:
                  return "\U000F007C";  // battery-30
                case 1:
                  return "\U000F007B";  // battery-20
                default:
                  return "\U000F007A";  // battery-10
              }
            }

touchscreen:
  - platform: st7123
    i2c_id: bsp_bus
    interrupt_pin: GPIO23
    display: lcd
    update_interval: never
    reset_pin:
      pi4ioe5v6408: pi4ioe1
      number: 5      
    transform:
      swap_xy: true
      mirror_x: true
    calibration:
      x_min: 0
      x_max: 1280
      y_min: 0
      y_max: 720
    id: touch
      
esp_ldo:
  - voltage: 2.5V
    channel: 3

display:
  - platform: mipi_dsi
    id: lcd
    dimensions:
      height: 1280
      width: 720
    model: M5STACK-TAB5-V2
    rotation: 270°
    reset_pin:
      pi4ioe5v6408: pi4ioe1
      number: 4

output:
  - platform: ledc
    pin: GPIO22
    id: backlight_pwm
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

i2s_audio:
  - id: mic_bus
    i2s_lrclk_pin: GPIO29
    i2s_bclk_pin: GPIO27
    i2s_mclk_pin: GPIO30

audio_adc:
  - platform: es7210
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

microphone:
  - platform: i2s_audio
    id: tab5_microphone
    i2s_din_pin: GPIO28
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external

audio_dac:
  - platform: es8388
    id: es8388_dac

speaker:
  - platform: i2s_audio
    id: tab5_speaker
    i2s_dout_pin: GPIO26
    audio_dac: es8388_dac
    dac_type: external
    channel: mono
    buffer_duration: 100ms
    bits_per_sample: 16bit
    sample_rate: 48000

media_player:
  - platform: speaker
    name: "Tab5"
    id: speaker_player
    announcement_pipeline:
      speaker: tab5_speaker
      format: FLAC
      sample_rate: 48000
      num_channels: 1

time:
  - platform: homeassistant
    id: ha_time
    on_time_sync:
      then:
        rx8130.write_time:
  - platform: rx8130
    id: rx8130_time
    update_interval: never
    on_time:
      # Update once ready
      - seconds: /3
        then:
          - lvgl.label.update:
              id: time_label
              text: !lambda |-
                auto t = id(ha_time).now();
                return t.strftime("%H:%M").c_str();

          - lvgl.label.update:
              id: date_label
              text: !lambda |-
                auto t = id(ha_time).now();
                return t.strftime("%Y-%m-%d %a").c_str();

text_sensor:
## Floor Lamp ##
  - platform: homeassistant
    id: floor_light
    entity_id: switch.standing_lamp_plug_mini
    on_value:
      then:
        - lvgl.widget.update:
            id: floor_light_btn
            state:
              checked: !lambda return x == "on";
              disabled: !lambda return ( x == "unavailable" ) or ( x == "unknown" );
        - lvgl.widget.update:
            id: floor_light_click_area
            clickable: !lambda return !((x == "unavailable") || (x == "unknown"));
        - lvgl.label.update:
            id: floor_light_label
            text_color: !lambda |-
              if ( x == "on" ) {
                  return lv_color_hex(0xFFF8DC);
              } else {
                  return lv_color_hex(0x9E9E9E);
              }
            text: !lambda |-
                static char buf[10];
                std::string icon;
                if ( x == "on" ) {
                    icon = "\U000F08DD";
                } else {
                    icon = "\U000F17C8";
                }
                snprintf(buf, sizeof(buf), "%s", icon.c_str());
                return buf;
        - lvgl.label.update:
            id: floor_light_status
            text: !lambda |-
                static char buf[10];
                std::string text;
                if ( x == "on" ) {
                    text = "ON";
                } 
                else if ( x == "unavailable" ||  x == "unknown" ) {
                    text = "UNKNOWN";
                }
                else {
                    text = "OFF";
                }
                snprintf(buf, sizeof(buf), "%s", text.c_str());
                return buf;
                
## Desk Lamp ##
  - platform: homeassistant
    id: desk_light
    entity_id: switch.desk_lamp
    on_value:
      then:
        - lvgl.widget.update:
            id: desk_light_btn
            state:
              checked: !lambda return x == "on";
              disabled: !lambda return ( x == "unavailable" ) or ( x == "unknown" );
        - lvgl.widget.update:
            id: desk_light_click_area
            clickable: !lambda return !((x == "unavailable") || (x == "unknown"));
        - lvgl.label.update:
            id: desk_light_label
            text_color: !lambda |-
              if ( x == "on" ) {
                  return lv_color_hex(0x008000);
              } else {
                  return lv_color_hex(0x9E9E9E);
              }
            text: !lambda |-
                static char buf[10];
                std::string icon;
                if ( x == "on" ) {
                    icon = "\U000F1B20";
                } else {
                    icon = "\U000F095F";
                }
                snprintf(buf, sizeof(buf), "%s", icon.c_str());
                return buf;
        - lvgl.label.update:
            id: desk_light_status
            text: !lambda |-
                static char buf[10];
                std::string text;
                if ( x == "on" ) {
                    text = "ON";
                } 
                else if ( x == "unavailable" ||  x == "unknown" ) {
                    text = "UNKNOWN";
                }
                else {
                    text = "OFF";
                }
                snprintf(buf, sizeof(buf), "%s", text.c_str());
                return buf;
